### ISSUE TITLE
Empty profile in post-regphase 

### ISSUE THREAD

**Issue by Corborax** [eurofurence/dealer-registration#20]
If a dealer post-Regphase was created via the admin as their assistant and then upgraded via Admin UI to the dealer, this application has no profile, so in the app export all Attends * fields remain empty. 

Since this was not a defined state so far, this has now been fixed in the apps so that dealers who would not be present on any day according to the data are displayed as present on all days, since the alternative would be the cancellation of their reg (a dealer without attendance days otherwise effectively does not participate and would be canceled by us; in addition, the state can only come about through this detour, since we prevent in the profile that all three days are deselected).

We should still fix this in the DD Reg by checking for applications when changing the type whether a profile exists for it and creating one if none exists and the new type is Share or Dealer.

**Comment by Fenrikur** [comment]
@Corborax as it says "post-Regphase" in the first sentence, could we maybe move this to the regular ef28 milestone (https://github.com/eurofurence/dealer-registration/milestone/2) as it's not necessary to be completed before reg starts?
